@startuml DocumentViever

title PipeSim SSO C4 Level 1

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!include template\C4_Container.puml
!include template\C4_Context.puml
!include template\C4_Component.puml

'LAYOUT_TOP_DOWN
'LAYOUT_LEFT_RIGHT
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

skinparam wrapWidth 200
skinparam maxMessageSize 200


Person(mainuser, "User", "Azure AD Account")


System_Boundary(fieldAp, "FieldAp"){
    
    System(fieldApLogon, "FieldAp Web", "")
    
    
}


System_Boundary(azureAd, "Azure AD"){   
    
    System(azureAD, "Equinor Azure Ad", "API")            
   

}

 System_Boundary(pipeSim, "PipeSim"){   
        System(pipeSimLogin, "PipeSim", "Software As A  Service (SLB Domain)")
       
 }

Rel(mainuser, fieldApLogon, "")
 

'Pipesim
Rel(pipeSimLogin, azureAD, "Request")


' Ad
Rel(azureAD, pipeSimLogin, "Token")
Rel(azureAD, fieldApLogon, "Token OK ")

'fieldAp
Rel(fieldApLogon, azureAD, "Request")

Rel(fieldApLogon, pipeSimLogin, "Forward")
@enduml