@startuml DocumentViever

title Resource Pool Management - RPM C4 Level 1

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!include template\C4_Container.puml
!include template\C4_Context.puml
!include template\C4_Component.puml

LAYOUT_TOP_DOWN
'LAYOUT_LEFT_RIGHT
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

skinparam wrapWidth 200
skinparam maxMessageSize 200


Person(mainuser, "User", "Azure AD Account")
Person(taskOwner, "Task Owner", "Azure AD Account")
Person(resourceOwner, "Resource Owner", "Azure AD Account")
Person(masterDataManager, "Masterdata Manager", "SAP Account")

System_Boundary(fusion, "Fusion Ecosystem"){
    
    System(rpm, "Resource Pool Management", "Fusion SPA")
    ContainerDb(rpmDb, "RPM Database", "Azure")

    System_Boundary(fusionCoreService, "Fusion Core Service"){
        System(orgChart, "Fusion Org Chart")
        System(meeting, "Fusion Meeting")
        System(appn, "Fusion App n")
    }
}


System_Boundary(other, "Other Systems"){   
    
    System(commonLib, "CommonLibrary", "API")            
    System(pims, "Pims", "API")
    System(azureAD, "Azure AD", "User Authentication API")

    System_Boundary(sapSystem, "SAP Systems"){   
        System(sapApi, "Sap API", "Omnia")
        System(sapSkill, "Skills", "P@E")
        System(sapEducation, "Formal Education", "P@E")
        System(sapCource, "Equinor University Completed Cource", "P@E")
    }
    System_Boundary(snow, "Service Now"){
    
        System(snowKitchen, "Kitchen View", "Application") 
        System(snowApi, "API")            
        System(snowServiceCatelogue, "Service Catalogue", "Masterdata")
        System(snowSoftwareinventory, "Software Inventory Catalogue", "Masterdata")

    'System(snowTask, "RITM. ENQ, etc.", "Default objects")
    
}
}



'snow
Rel(snowApi, snowServiceCatelogue, "")
Rel(snowApi, snowSoftwareinventory, "")

'SAP
Rel(sapApi, sapSkill, "")
Rel(sapApi, sapEducation, "")
Rel(sapApi, sapCource, "")


'External
Rel(rpm,commonLib,"")
Rel(rpm, sapApi, "")
Rel(rpm, pims, "")

'Fusion Internal
Rel(rpm, rpmDb, "")
Rel(rpm, orgChart, "")
Rel(rpm, meeting, "")
Rel(rpm, appn, "")
Rel(rpm, snowApi, "")
Rel(rpm, azureAD, "")

'users
Rel(mainuser, rpm, "")
Rel(taskOwner, rpm, "")
Rel(resourceOwner, rpm, "")
Rel(masterDataManager, snowKitchen, "")
Rel(snowKitchen, snowServiceCatelogue, "")



@enduml